apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ctlptl-registry
port: 5005
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: kind-dev
product: kind
kubernetesVersion: v1.22.0
registry: ctlptl-registry
