apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "cattage.fullname" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cattage.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ template "cattage.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
    - {{ template "cattage.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ template "cattage.fullname" . }}-selfsigned-issuer
  secretName: webhook-server-cert
