apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "cattage.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cattage.labels" . | nindent 4 }}
spec:
  selfSigned: {}
