# permissions for end users to view tenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - cattage.cybozu.io
  resources:
  - tenants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cattage.cybozu.io
  resources:
  - tenants/status
  verbs:
  - get
