apiVersion: v1
kind: Pod
metadata:
  name: testhttpd
  namespace: sub-1
spec:
  containers:
  - image: ghcr.io/cybozu/testhttpd:0.2.3
    imagePullPolicy: IfNotPresent
    name: testhttpd
    ports:
    - containerPort: 8000
      protocol: TCP
