controller:
  config:
    labelKeys:
      - multi-tenancy.cybozu.com/tenant
    watches:
      - group: rbac.authorization.k8s.io
        version: v1
        kind: Role
      - group: rbac.authorization.k8s.io
        version: v1
        kind: RoleBinding
