apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample
  namespace: sub-1
  labels:
    foo: bar
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: a-team
  source:
    repoURL: https://github.com/cybozu-go/cattage.git
    targetRevision: main
    path: samples/argocd-config
  destination:
    server: https://kubernetes.default.svc
    namespace: sub-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
