apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample
  namespace: app-sample
  labels:
    foo: bar
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tenant-sample
  source:
    repoURL: https://github.com/neco-test/apps-sandbox.git
    targetRevision: master
    path: testhttpd
  destination:
    server: https://kubernetes.default.svc
    namespace: app-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
