name: "Setup tools"
description: "Setup tools with aqua"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
runs:
  using: composite
  steps:
    - uses: aquaproj/aqua-installer@a34cc75221784a96e3caf4bbf716ff67a160a3f1 #v1.0.0
      with:
        aqua_version: v1.1.0
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
