name: "Setup tools"
description: "Setup tools with aqua"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
runs:
  using: composite
  steps:
    - uses: aquaproj/aqua-installer@58fc6b885cba1f956127fa2b40d64eea0400bf7b #v0.7.0
      with:
        aqua_version: v0.10.2
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
