[book]
language = "en"
multilingual = false
src = "."
title = "neco-tenant-controller Documentation"

[output.html]
git-repository-url = "https://github.com/cybozu-go/neco-tenant-controller"
edit-url-template = "https://github.com/cybozu-go/neco-tenant-controller/edit/main/docs/{path}"
site-url = "/neco-tenant-controller/"
