resources:
- ../../rbac
- ../../webhook

namespace: '{{ .Release.Namespace }}'

namePrefix: '{{ template "cattage.fullname" . }}-'



transformers:
- label-transformer.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: '{{ include "cattage.name" . }}'
patches:
- path: webhookcainjection_patch.yaml
