name: Release Charts
on:
  push:
    tags:
      - 'chart-v*'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: aquaproj/aqua-installer@58fc6b885cba1f956127fa2b40d64eea0400bf7b #v0.7.0
        with:
          aqua_version: v0.10.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check chart version
        run: |
          tag_version=${GITHUB_REF##*/chart-v}
          chart_version=$(cat charts/cattage/Chart.yaml | grep 'version:' | sed 's/version:\s//')
          if [ "$tag_version" != "$chart_version" ]; then
            echo "Different versions: tag \"$tag_version\", chart \"$chart_version\""
            exit 1
          fi
      - name: Packaging the chart
        run: helm package ./charts/cattage/
      - uses: actions/upload-artifact@v2
        with:
          name: helm-charts
          path: ./cattage-*.tgz
          retention-days: 1
  publish:
    name: Publish charts on GitHub Pages
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: aquaproj/aqua-installer@58fc6b885cba1f956127fa2b40d64eea0400bf7b #v0.7.0
        with:
          aqua_version: v0.10.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v2
        with:
          name: helm-charts
      - name: Update charts index
        run: helm repo index --url https://cybozu-go.github.io/cattage/ --merge index.yaml .
      - run: git add .
      - name: Check diffs
        run: |
          diffs=$(git status -s)
          if [ "$diffs" = "" ]; then
            echo "NO_DIFF=1" >> $GITHUB_ENV
          else
            printf "%s\n" "$diffs"
          fi
      - name: Commit changes
        if: env.NO_DIFF != '1'
        run: |
          git config --global user.name 'Cybozu Neco'
          git config --global user.email 'cybozu-neco@users.noreply.github.com'
          git commit -m 'update'
      - name: Push to gh-pages
        if: env.NO_DIFF != '1'
        run: git push origin gh-pages
