name: Release
on:
  push:
    tags:
    - 'v*'
env:
  go-version: 1.17
jobs:
  image:
    name: Push Container Image
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build images
      run: |
        docker build -t neco-tenant-controller:dev .
    - name: Login to ghcr.io
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - name: Push images
      run: |
        TAG=${GITHUB_REF#refs/tags/v}
        docker tag neco-tenant-controller:dev ghcr.io/cybozu-go/neco-tenant-controller:$TAG
        docker push ghcr.io/cybozu-go/neco-tenant-controller:$TAG
