name: Renovate
on:
  schedule:
    - cron: '0 30 * * 1'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@a1ed1d0adddfdf138192d1fbe3150a80094dee6a # renovate v40.3.1
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
